//  <auto-generated/> 

using MQTTnet.Client;
using MQTTnet.Extensions.MultiCloud;
using MQTTnet.Extensions.MultiCloud.AwsIoTClient;
using MQTTnet.Extensions.MultiCloud.AwsIoTClient.TopicBindings;
using MQTTnet.Extensions.MultiCloud.BrokerIoTClient;

namespace dtmi_rido_pnp_memmon.aws;

public class memmon : AwsMqttClient, Imemmon
{
    public IReadOnlyProperty<DateTime> Property_started { get; set; }
    public IWritableProperty<bool> Property_enabled { get; set; }
    public IWritableProperty<int> Property_interval { get; set; }
    public ITelemetry<double> Telemetry_workingSet { get; set; }
    public ICommand<Cmd_getRuntimeStats_Request, Cmd_getRuntimeStats_Response> Command_getRuntimeStats { get; set; }

    public string InitialState => String.Empty;

    internal memmon(IMqttClient c) : base(c, Imemmon.ModelId)
    {
        Property_started = new ReadOnlyPropertyUTFJson<DateTime>(c, "started");
        Property_interval = new WritablePropertyUTFJson<int>(c, "interval");
        Property_enabled = new AwsWritablePropertyUTFJson<bool>(c, "enabled");
        Telemetry_workingSet = new TelemetryUTF8Json<double>(c, "workingSet");
        Command_getRuntimeStats = new CommandUTF8Json<Cmd_getRuntimeStats_Request, Cmd_getRuntimeStats_Response>(c, "getRuntimeStats");
    }
}