//  <auto-generated/> 


using MQTTnet.Client;
using MQTTnet.Extensions.MultiCloud;
using System.Runtime.CompilerServices;

namespace dtmi_rido_pnp_memmon;

public interface Imemmon 
{
    public const string ModelId = "dtmi:rido:pnp:memmon;1";
    public IMqttClient Connection { get; }
    public string InitialState { get; }
    public IReadOnlyProperty<DateTime> Property_started { get; set; }
    public IWritableProperty<bool> Property_enabled { get; set; }
    public IWritableProperty<int> Property_interval { get; set; }
    public ITelemetry<double> Telemetry_workingSet { get; set; }
    public ICommand<Cmd_getRuntimeStats_Request, Cmd_getRuntimeStats_Response> Command_getRuntimeStats { get; set; }
}

public enum DiagnosticsMode
{
    minimal = 0,
    complete = 1,
    full = 2
}

public class Cmd_getRuntimeStats_Request : IBaseCommandRequest<Cmd_getRuntimeStats_Request>
{
    public DiagnosticsMode DiagnosticsMode { get; set; }

    public Cmd_getRuntimeStats_Request DeserializeBody(string payload)
    {
        return new Cmd_getRuntimeStats_Request()
        {
            DiagnosticsMode = Json.FromString<DiagnosticsMode>(payload)
        };
    }

    public Cmd_getRuntimeStats_Request DeserializeBody(byte[] payload)
    {
        throw new NotImplementedException();
    }
}

public class Cmd_getRuntimeStats_Response : IBaseCommandResponse
{
    //ReponsePayload = new Dictionary<string, string>();
    
    public int Status { get; set; }
    public object ReponsePayload { get; set; }
    public byte[] ResponseBytes { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
}
