//  <auto-generated/> 


using MQTTnet.Client;
using MQTTnet.Extensions.MultiCloud;
using MQTTnet.Extensions.MultiCloud.AzureIoTClient;
using pnp_memmon;

namespace dtmi_rido_pnp_memmon.hub;

public class memmon : HubMqttClient, Imemmon
{
    public IReadOnlyProperty<DateTime> Property_started { get; set; }
    public IWritableProperty<bool> Property_enabled { get; set; }
    public IWritableProperty<int> Property_interval { get; set; }
    public ITelemetry<double> Telemetry_workingSet { get; set; }
    public ICommand<Cmd_getRuntimeStats_Request, Cmd_getRuntimeStats_Response> Command_getRuntimeStats { get; set; }

    public memmon(IMqttClient c) : base(c)
    {
        Property_started = new HubReadOnlyPropertyUTFJson<DateTime>(c, "started");
        Property_interval = new HubWritablePropertyUTFJson<int>(c, "interval");
        Property_enabled = new HubWritablePropertyUTFJson<bool>(c, "enabled");
        Telemetry_workingSet = new HubTelemetryUTF8Json<double>(c, "workingSet");
        Command_getRuntimeStats = new HubCommandUTF8Json<Cmd_getRuntimeStats_Request, Cmd_getRuntimeStats_Response>(c, "getRuntimeStats");
    }
}