//  <auto-generated/> 

using MQTTnet.Client;
using MQTTnet.Extensions.MultiCloud;
using MQTTnet.Extensions.MultiCloud.BrokerIoTClient.Command;
using MQTTnet.Extensions.MultiCloud.BrokerIoTClient.ReadOnlyProperty;
using MQTTnet.Extensions.MultiCloud.BrokerIoTClient.Telemetry;
using MQTTnet.Extensions.MultiCloud.BrokerIoTClient.WritableProperty;

namespace dtmi_rido_pnp_sensehat.mqtt;

public class sensehat : Isensehat
{
    public IMqttClient Connection { get; set; }
    public string InitialState { get; set; }
    public IReadOnlyProperty<string> Property_piri { get; set; }
    public IReadOnlyProperty<string> Property_ipaddr { get; set; }
    public IReadOnlyProperty<string> Property_sdkInfo { get; set; }
    public IWritableProperty<int> Property_interval { get; set; }
    public IWritableProperty<bool> Property_combineTelemetry { get; set; }
    public ITelemetry<double> Telemetry_t1 { get; set; }
    public ITelemetry<double> Telemetry_t2 { get; set; }
    public ITelemetry<double> Telemetry_h { get; set; }
    public ITelemetry<double> Telemetry_p { get; set; }
    public ITelemetry<double> Telemetry_m { get; set; }

    public ITelemetry<AllTelemetries> AllTelemetries;

    public ICommand<string,string> Command_ChangeLCDColor { get; set; }

    

    internal sensehat(IMqttClient c) 
    {
        Connection = c;
        Property_piri = new ReadOnlyPropertyUTFJson<string>(c, "piri");
        Property_ipaddr = new ReadOnlyPropertyUTFJson<string>(c, "ipaddr");
        Property_sdkInfo = new ReadOnlyPropertyUTFJson<string>(c, "sdkInfo");
        Property_combineTelemetry = new WritablePropertyUTFJson<bool>(c, "combineTelemetry");
        Property_interval = new WritablePropertyUTFJson<int>(c, "interval");
        Telemetry_t1 = new TelemetryUTF8Json<double>(c, "t1");
        Telemetry_t2 = new TelemetryUTF8Json<double>(c, "t2");
        Telemetry_h = new TelemetryUTF8Json<double>(c, "h");
        Telemetry_p = new TelemetryUTF8Json<double>(c, "p");
        Command_ChangeLCDColor = new CommandUTF8Json<string,string>(c, "ChangeLCDColor");
        AllTelemetries = new TelemetryUTF8Json<AllTelemetries>(c, String.Empty)
        {
            wrapMessage = false
        };
    }

    public async Task SendTelemetryAsync(AllTelemetries payload, CancellationToken t = default)
    {
        await AllTelemetries.SendMessageAsync(payload, t);
    }
}