// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace payload_size.avros
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class Properties : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Properties\",\"namespace\":\"AvroTests\",\"fields\":[{\"name\":\"S" +
				"dkInfo\",\"type\":[\"null\",\"string\"]},{\"name\":\"Started\",\"type\":\"long\"}]}");
		private string _SdkInfo;
		private long _Started;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return Properties._SCHEMA;
			}
		}
		public string SdkInfo
		{
			get
			{
				return this._SdkInfo;
			}
			set
			{
				this._SdkInfo = value;
			}
		}
		public long Started
		{
			get
			{
				return this._Started;
			}
			set
			{
				this._Started = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.SdkInfo;
			case 1: return this.Started;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.SdkInfo = (System.String)fieldValue; break;
			case 1: this.Started = (System.Int64)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
