//  <auto-generated/> 

using MQTTnet.Client;
using MQTTnet.Extensions.MultiCloud;
using MQTTnet.Extensions.MultiCloud.AzureIoTClient;

namespace dtmi_com_example_devicetemplate.hub;

public class devicetemplate : HubMqttClient, Idevicetemplate
{
    public IReadOnlyProperty<string> Property_sdkInfo { get; set; }
    public IWritableProperty<int> Property_interval { get ; set ; }
    public ITelemetry<double> Telemetry_temp { get ; set ; }
    public ICommand<string, string> Command_echo { get; set; }

    public devicetemplate(IMqttClient c) : base(c)
    {
        Property_sdkInfo = new HubReadOnlyPropertyUTFJson<string>(c, "sdkInfo");
        Property_interval = new HubWritablePropertyUTFJson<int>(c, "interval");
        Telemetry_temp = new HubTelemetryUTF8Json<double>(c, "temp");
        Command_echo = new HubCommandUTF8Json<string, string>(c, "echo");
    }
}
