name: cd

on:
  push:
    branches: [ "master", "dev" ]
    paths-ignore:
      - 'docs/**'
      - 'samples/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          6.0.x
          3.1.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Pack
      run: dotnet pack -c Release -o _nupkgs

    - name: Push MyGet
      run: cd _nupkgs && dotnet nuget push * --api-key ${{ secrets.MYGET_TOKEN }} --source https://www.myget.org/F/ridopackages/api/v2/package --skip-duplicate --no-symbols

    - name: Annotate Versions
      run: |
        echo " ## Packages Pushed to MyGet :gem: " >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo " with version {{ steps.nbgv.NuGetPackageVersion }}" >> $GITHUB_STEP_SUMMARY
        echo " from commit {{ steps.nbgv.GitCommitId}}" >> $GITHUB_STEP_SUMMARY