name: ci

on:
  pull_request:
    branches: [ "*" ]
    paths-ignore:
      - '*'
      - 'docs/**'
      - 'samples/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Test_IoT_Hub
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          6.0.x
          3.1.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: start mosquitto local
      run: docker run -d --rm -p 8080:8080 -p 1883:1883 -p 8883:8883 -p 8884:8884 -p 8443:8443  ridomin/mosquitto-local:dev

    - name: Test
      env:
        E2EHubConnectionString: ${{secrets.E2EHubConnectionString}}
        TestHubName: ${{secrets.TestHubName}} 
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" --filter FullyQualifiedName!=MQTTnet.Extensions.MultiCloud.IntegrationTests.e2e

    - name: Pack
      run: dotnet pack -c Release -o _nupkgs