name: memmon-docker

on:
  push:
    branches: [ "master", "dev" ]
    paths:
      - 'samples/memmon/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file samples/memmon/Dockerfile --tag ghcr.io/ridomin/memmon:x64
    - name: push image
      run: docker push ghcr.io/ridomin/memmon:x64
    #- name: Build the Docker image ARM
    #  run: docker build . --file samples/memmon/Dockerfile.pi --tag ghcr.io/ridomin/memmon:arm
    - name: push image arm
      run: docker push ghcr.io/ridomin/memmon:arm