name: samples-docker

on:
  push:
    branches: [ "master", "dev" ]
    paths:
      - 'samples/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: memmon docker
      run: docker build . --file samples/memmon/Dockerfile --tag ghcr.io/iotmodels/memmon:x64

    - name: memmon docker push 
      run: docker push ghcr.io/iotmodels/memmon:x64

    - name: pi-sense docker
      run: docker build . --file samples/pi-sense-device/Dockerfile --tag ghcr.io/iotmodels/pi-sense-device:x64

    - name: pi-sense docker push 
      run: docker push ghcr.io/iotmodels/pi-sense-device:x64


    #- name: Build the Docker image ARM
    #  run: docker build . --file samples/memmon/Dockerfile.pi --tag ghcr.io/ridomin/memmon:arm
    #- name: push image arm
    #  run: docker push ghcr.io/iotmodels/memmon:arm